# Getting started with MemsArray object

In [1]:
import numpy as np
from megamicros.log import log
from megamicros.core.base import MemsArray
from megamicros.bmf import Beamformer

log.setLevel( "INFO" )

# Declare a 32 MEMs antenna
antenna = MemsArray( available_mems_number=32 )

# verify available mems number
print( f"available mems number={antenna.available_mems_number}" )

# set active mems
antenna.setActiveMems( [i for i in range(32)] )
print( f"active mems number={antenna.mems_number}" )

# iterate over the antenna data stream
for i, data in enumerate( antenna ):
    print( f"data={data}")
    if i > 10:
        break

mems = np.load ('Antenna-square-Xm_Cohrmds.npy' )

bmf = Beamformer( 
    mems_position = mems,
    sampling_frequency = 10000,
    window_size = 256,
    space_quantization = [2, 2.1, 0],
    space_size = [5, 5, 2.02]
)



bmf.setSamplingFrequency( 10000 )
#bmf.init()






2023-09-07 00:05:53,164 [INFO]:  .Set beamformer sampling rate on 10000 Hz
2023-09-07 00:05:53,165 [INFO]:  .Set beamformer FFT window size to 256 samples
2023-09-07 00:05:53,165 [INFO]:  .Set beamformer space quantization to [2, 2.1, 0] locations/meter
2023-09-07 00:05:53,166 [INFO]:  .Set beamformer space size to [5, 5, 2.02]
2023-09-07 00:05:53,169 [INFO]:  .Set beamformer sampling rate on 10000 Hz


available mems number=32
active mems number=32
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ..