# Getting started with MemsArrayNP objects

The `MemsArrayNP` derived from the `MemsArray` class while being very similar.
While `MemsArray` objects cannot generate any signals except random ones,`MemsArrayNP` can get their signals from numpy array data.

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from megamicros_tools.log import log
from megamicros.core.np import MemsArrayNP

log.setLevel( "INFO" )

Let's create an array of random data aiming at simulate signals from a 32 MEMs antenna.

In [9]:
data = np.random.rand( 100000, 32 )
data.shape

(100000, 32)

Create the antenna

In [3]:
antenna = MemsArrayNP( data )

2024-02-25 10:53:40,106 [INFO]:  .Install MemsArrayNP settings
2024-02-25 10:53:40,107 [INFO]:  .Install MemsArray settings
2024-02-25 10:53:40,108 [INFO]:  .Created a new antenna
2024-02-25 10:53:40,108 [INFO]:  .MemsArrayNP object created with input array 100000 data x 32 channels


Specify avalable the 32 MEMs channels and activate them:

In [10]:
antenna.setAvailableMems( 32 )
antenna.setActiveMems( [i for i in range(32)] )

2024-02-25 10:56:09,590 [INFO]:  .Set 32 available MEMs numbered from 0 to 31
2024-02-25 10:56:09,592 [INFO]:  .32 MEMs were activated among 0 to 31 available MEMs


Run on two seconds duration.

In [12]:
antenna.run( duration=2, datatype='float32' )

# get data, loop is blocking
for data in antenna:
    print( f"data={data}" )

# Wait until the thread terminates
antenna.wait()

2024-02-25 10:56:31,194 [INFO]:  .Starting run execution
2024-02-25 10:56:31,195 [INFO]:  .Install MemsArrayNP settings
2024-02-25 10:56:31,196 [INFO]:  .Install MemsArray settings
2024-02-25 10:56:31,197 [INFO]:  .Set datatype to float32 
2024-02-25 10:56:31,198 [INFO]:  .Pre-execution checks for MemsArray.run()
2024-02-25 10:56:31,198 [INFO]:  .Pre-execution checks for MemsArray.run()
2024-02-25 10:56:31,198 [INFO]:  .Requested job: run
2024-02-25 10:56:31,199 [INFO]:  .Pre-execution checks for MemsArrayNP.run()
2024-02-25 10:56:31,199 [INFO]:  .Perform a 2s run loop
2024-02-25 10:56:31,200 [INFO]:  .Frame length: 256 samples (chunk size: 5120 Bytes)
2024-02-25 10:56:31,200 [INFO]:  .Sampling frequency: 50000 Hz
2024-02-25 10:56:31,201 [INFO]:  .Active MEMs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
2024-02-25 10:56:31,201 [INFO]:  .Active analogic channels: []
2024-02-25 10:56:31,201 [INFO]:  .Whether count

mask: [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
mask(2): [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
masking: False
data=[[0.76275915 0.6354922  0.49830765 ... 0.2654582  0.5611146  0.45420146]
 [0.03254877 0.07947097 0.5932953  ... 0.29736584 0.56960136 0.95010895]
 [0.3690691  0.39035797 0.54026186 ... 0.5674055  0.15207422 0.22586712]
 ...
 [0.08748229 0.1033233  0.65752345 ... 0.984241   0.5236679  0.29773122]
 [0.74236846 0.3646326  0.20020993 ... 0.09527138 0.8393631  0.01649567]
 [0.33689806 0.9624674  0.44040242 ... 0.93086314 0.03930486 0.5477897 ]]
data=[[0.8165042  0.03943215 0.62521046 ... 0.21494785 0.2507933  0.2547052 ]
 [0.38324332 0.25441575 0.55183387 ... 0.81858504 0.21515

2024-02-25 10:56:33,177 [INFO]:  .Running stopped: normal thread termination
2024-02-25 10:56:33,178 [INFO]:  .Elapsed time: 1.9747471809387207s (expected duration was: 2 s)
2024-02-25 10:56:33,178 [INFO]:  .Proceeded to 390 transfers
2024-02-25 10:56:33,179 [INFO]:  .Run completed
2024-02-25 10:56:33,207 [INFO]:  .Thread timer started for 2s duration


data=[[0.88632995 0.8485632  0.4792256  ... 0.7078995  0.766898   0.7698251 ]
 [0.45125896 0.3502422  0.22909456 ... 0.22587788 0.8159422  0.8347646 ]
 [0.5387232  0.68780786 0.63399863 ... 0.90893    0.56388855 0.2475956 ]
 ...
 [0.7967465  0.3668975  0.68412143 ... 0.6195409  0.08556184 0.31770435]
 [0.7909078  0.24611902 0.83951145 ... 0.05196599 0.41295567 0.3631411 ]
 [0.46149656 0.3299543  0.04353433 ... 0.7647123  0.10651004 0.5817045 ]]
data=[[0.26810572 0.9702921  0.8042996  ... 0.9880992  0.74520296 0.9300085 ]
 [0.9032209  0.6354618  0.56872076 ... 0.07925171 0.03681517 0.4298765 ]
 [0.9256752  0.1595825  0.149873   ... 0.13341095 0.76176584 0.63848144]
 ...
 [0.91393125 0.17356697 0.7448827  ... 0.97882444 0.39039022 0.04054964]
 [0.820574   0.6950968  0.16009843 ... 0.77971244 0.08664672 0.5395226 ]
 [0.23136315 0.32192022 0.4579936  ... 0.57510483 0.23353088 0.912945  ]]
data=[[0.66798836 0.41986406 0.08903656 ... 0.42109555 0.10152817 0.06570952]
 [0.68611234 0.5895317  