# Getting started with MemsArray object

In [1]:
import numpy as np
from megamicros.log import log
from megamicros.core.base import MemsArray
from megamicros.bmf import Beamformer

log.setLevel( "INFO" )

# Declare a 32 MEMs antenna
antenna = MemsArray( available_mems_number=32 )

# verify available mems number
print( f"available mems number={antenna.available_mems_number}" )

# set active mems
antenna.setActiveMems( [i for i in range(32)] )
print( f"active mems number={antenna.mems_number}" )

# iterate over the antenna data stream
for i, data in enumerate( antenna ):
    print( f"data={data}")
    if i > 10:
        break

mems = np.load ('Antenna-square-JetsonNano-0001.npy' )

bmf = Beamformer( 
    mems_position = mems,
    sampling_frequency = 10000,
    window_size = 256,
    space_quantization = [2, 2.1, 1/2.02],
    space_size = [5, 5, 2.02]
)


bmf.setSamplingFrequency( 10000 )
bmf.init()



2023-09-07 15:34:06,179 [INFO]:  .Set beamformer on a 25 MEMs antenna
2023-09-07 15:34:06,180 [INFO]:  .Set beamformer sampling rate on 10000 Hz
2023-09-07 15:34:06,181 [INFO]:  .Set beamformer FFT window size to 256 samples
2023-09-07 15:34:06,182 [INFO]:  .Set beamformer space quantization to [2, 2.1, 0.49504950495049505] locations/meter
2023-09-07 15:34:06,183 [INFO]:  .Set beamformer space size to [5, 5, 2.02] meters
2023-09-07 15:34:06,190 [INFO]:  .Set beamformer sampling rate on 10000 Hz
2023-09-07 15:34:06,195 [INFO]:  .Checking beamformer parameters...
2023-09-07 15:34:06,204 [INFO]:  .[Ready]
2023-09-07 15:34:06,205 [INFO]:  .Beamformer2D Initilization:
2023-09-07 15:34:06,206 [INFO]:   > Found antenna with 25 MEMs microphones
2023-09-07 15:34:06,206 [INFO]:   > FFT window size is 256 samples
2023-09-07 15:34:06,207 [INFO]:   > Time range: [0, 0.0255] s
2023-09-07 15:34:06,212 [INFO]:   > Frequency range: [0, 5000.0] Hz (129 beams)
2023-09-07 15:34:06,215 [INFO]:   > Space qu

available mems number=32
active mems number=32
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
data=[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ..