# Getting started with MemsArrayNP objects

The `MemsArrayNP` derived from the `MemsArray` class while being very similar.
While `MemsArray` objects cannot generate any signals except random ones,`MemsArrayNP` can get their signals from numpy array data.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from megamicros_tools.log import log
from megamicros.core.np import MemsArrayNP

log.setLevel( "INFO" )

Let's create an array of random data aiming at simulate signals from a 32 MEMs antenna.

In [6]:
data = np.random.rand( 10000, 32 )
data.shape

(10000, 32)

Create the antenna

In [7]:
antenna = MemsArrayNP( data )

2024-02-25 00:30:26,955 [INFO]:  .Install MemsArrayNP settings
2024-02-25 00:30:26,957 [INFO]:  .Install MemsArray settings
2024-02-25 00:30:26,958 [INFO]:  .Created a new antenna
2024-02-25 00:30:26,958 [INFO]:  .MemsArrayNP object created with input array 10000 data x 32 channels


Specify avalable the 32 MEMs channels and activate them:

In [8]:
antenna.setAvailableMems( 32 )
antenna.setActiveMems( [i for i in range(32)] )

2024-02-25 00:30:29,677 [INFO]:  .Set 32 available MEMs numbered from 0 to 31
2024-02-25 00:30:29,678 [INFO]:  .32 MEMs were activated among 0 to 31 available MEMs


Run

In [9]:
antenna.run( duration=2 )

# get data, loop is blocking
for data in antenna:
    print( f"data={data}" )

# Wait until the thread terminates
antenna.wait()

2024-02-25 00:30:32,732 [INFO]:  .Starting run execution
2024-02-25 00:30:32,733 [INFO]:  .Install MemsArrayNP settings
2024-02-25 00:30:32,734 [INFO]:  .Install MemsArray settings
2024-02-25 00:30:32,735 [INFO]:  .Pre-execution checks for MemsArray.run()
2024-02-25 00:30:32,735 [INFO]:  .Pre-execution checks for MemsArray.run()
2024-02-25 00:30:32,736 [INFO]:  .Counter was not set -> set to False
2024-02-25 00:30:32,736 [INFO]:  .Counter skipping not set -> set to False
2024-02-25 00:30:32,737 [INFO]:  .Status was not set -> set to False
2024-02-25 00:30:32,738 [INFO]:  .Requested job: run
2024-02-25 00:30:32,738 [INFO]:  .Pre-execution checks for MemsArrayNP.run()
2024-02-25 00:30:32,738 [INFO]:  .Perform a 2s run loop
2024-02-25 00:30:32,739 [INFO]:  .Frame length: 256 samples (chunk size: 5120 Bytes)
2024-02-25 00:30:32,739 [INFO]:  .Sampling frequency: 50000 Hz
2024-02-25 00:30:32,739 [INFO]:  .Active MEMs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,

mask: [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
mask(2): [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
masking: False
ok
chunk: (10000, 32)
transfer_index: 0
chunk: (256, 32)
data=[[114180 123720  60338 ...  45765  93725 112264]
 [ 10392  74852 125060 ...  51240 129999  78937]
 [132385  15471  39249 ...  95602  50437  46890]
 ...
 [ 11372  23186  89158 ...  85102    753  57064]
 [ 94928  56745  43013 ... 108180  41303  48468]
 [ 16610  25489  72217 ... 124323   7870  82609]]
transfer_index: 1
chunk: (256, 32)
data=[[113973   6146  85887 ...  86462   1820  71850]
 [120885  64884  94732 ... 113700  36157  82959]
 [ 92429  62193  82106 ...   7771 115418 118721]
 ...
 [ 76506   3959  48509 ... 116

2024-02-25 00:30:34,746 [INFO]:  .Thread timer started for 2s duration
